%YAML:1.0 # need to specify the file type at the top!


# MTI-100 series converted from datasheet, guess on bias random walk
# https://www.xsens.com/hubfs/Downloads/usermanual/MTi_usermanual.pdf

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
#  accelerometer_noise_density: 2.0000e-03  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
#  accelerometer_random_walk: 3.0000e-03    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
#  gyroscope_noise_density: 1.6968e-04      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
#  gyroscope_random_walk: 1.9393e-05        # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 5.8860e-03  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 1.0000e-04    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 1.7453e-04      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk:  1.0000e-05      # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  model: calibrated
  rostopic: /imu/data_raw
  time_offset: 0.0
  update_rate: 500.0